### ISSUE TITLE
Votação para o Logo do Grupo

### ISSUE THREAD

**Issue by woliveiras** [front-abc/frontabc#5]
# Votação para o logo do Grupo

Basta adicionar um comentário com a opção (**1**, **2**, **3**, **4**) e o **+1**.

Ex.: `Opção 1, **+1**`.

## Opção 1:

![frontabc-1](https://cloud.githubusercontent.com/assets/4243601/11483318/e8a03ed0-978e-11e5-9674-10a301db7016.gif)

------

## Opção 2:

![frontabc-2](https://cloud.githubusercontent.com/assets/4243601/11483336/fe8b129c-978e-11e5-96d1-77ed9dc1f7db.gif)

------

## Opção 3:

![frontabc-3](https://cloud.githubusercontent.com/assets/4243601/11483341/0995e2ac-978f-11e5-8c25-96c3442a48ea.gif)

------

## Opção 4:

![frontabc-4](https://cloud.githubusercontent.com/assets/4243601/11483346/11aef71c-978f-11e5-9719-584b78edbc2d.gif)

**Comment by DWoonD** [comment]
1

**Comment by wmsbill** [comment]
1 - por que parece com o chrome

**Comment by ubirajarapelli** [comment]
3 - Tenho que ter no mínimo o meu voto!

**Comment by woliveiras** [comment]
As ideia desse Ubira... kkkkk

**Comment by carmona** [comment]
Opção 1, **+1**

**Comment by ramirodss** [comment]
1 +1

**Comment by leandrofsp** [comment]
4

**Comment by teles** [comment]
Opção 1.

**Comment by wesleycoder** [comment]
Opção 1: +1.

**Comment by marquinhusgoncalves** [comment]
**Opção 1: + 1.
Obs.:** Concordo com o @DWoonD se o cubo tivesse com as da opção 1 ficaria bacana.

**Comment by ubirajarapelli** [comment]
Eu e o @felipeuliana  podemos fazer um nesse esquema @marquinhusgoncalves / @DWoonD

**Comment by dhelbegor** [comment]
__Opção 1: +1__

**Comment by massilva** [comment]
Opção 1, +1

**Comment by Cleysonlb** [comment]
Opção 1, +1

**Comment by woliveiras** [comment]
Ai sim @ubirajarapelli. Taca pau junto com o mano @felipeuliana que vai ficar muito shooow!

**Comment by tamihh** [comment]
*Opção 2:* +1

*Obs.:* Concordo com o @DWoonD <https://github.com/DWoonD> se o cubo
tivesse com as da opção 1 ficaria bacana.[2]
ᐧ

2015-11-30 20:27 GMT-02:00 William Oliveira <notifications@github.com>:

**Comment by brunosalgueiro** [comment]
1+1

**Comment by fbadaro** [comment]
Eu prefiro a primeira opção mesmo.

Opção 1, +1

**Comment by maugravena** [comment]
opção 3, +1

obs: o primeiro lembra demais o google

**Comment by danvitoriano** [comment]
Opção 1

**Comment by wmsbill** [comment]
Cadê o D?

**Comment by rkb81** [comment]
Cade a defesa de cada logo? desculpe a franquesa, mas designer que se preza deveria defender o próprio design e não somente fazer alguns desenhos e jogar a ideia.

**Comment by felipeuliana** [comment]
A pedido do @rkb81 Eis aqui a defesa do logtipo 'Opçaõ 1'.

"A base para o desenvolvimento Front End são suas principais tecnologias, basicamente o HTML, o CSS e o JavaScript.
As mesmas são evidenciadas no logotipo através de suas cores, empiricamente conhecidas pela comunidade, o laranja, o azul e o amarelo.
Para personificar as três tecnologias, visualizei as mesmas como três forças, que matematicamente podem ser expressadas como vetores, o que me remeteu a 'setas'.
Buscando um modo de equilibar as três 'forças', foi feita a composição das 'setas' em um hexágono, com cada 'seta' em um sentido equilibrando uma a outra.
E também, entremeando-se afim de denotar que as três interagem entre si."

Então é isso! Abraços! \m/

**Comment by woliveiras** [comment]
Foda ein...
Bira e Brutinhos de parabéns!

**Comment by gecisant** [comment]
1+1

**Comment by rkb81** [comment]
1+1
